CREATE TABLE IF NOT EXISTS BUSINESS_TRANSACTION
(
   DATE DATE,
   ID VARCHAR PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS INVOICE
(
   TOTAL_AMOUNT FLOAT(53),
   ID VARCHAR PRIMARY KEY,
   CUSTOMER_ID VARCHAR
);
CREATE TABLE IF NOT EXISTS INVOICE_LINE
(
   PRODUCT_CODE VARCHAR,
   QUANTITY INTEGER,
   PURCHASE_PRICE FLOAT(53),
   ID VARCHAR PRIMARY KEY,
   PRODUCT_CODE VARCHAR,
   INVOICE_ID VARCHAR
);
CREATE TABLE IF NOT EXISTS PRODUCT
(
   CODE VARCHAR PRIMARY KEY,
   LABEL VARCHAR,
   CATALOG_PRICE FLOAT(53)
);
CREATE TABLE IF NOT EXISTS CUSTOMER
(
   NAME VARCHAR,
   ID VARCHAR PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS RECEIPT
(
   ID VARCHAR PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS RECEIPT_LINE
(
   QUANTITY INTEGER,
   STORE_PURCHASE_PRICE FLOAT(53),
   ID VARCHAR PRIMARY KEY,
   PRODUCT_CODE VARCHAR,
   RECEIPT_ID VARCHAR
);
CREATE TABLE IF NOT EXISTS STORE
(
   CODE VARCHAR PRIMARY KEY,
   LABEL VARCHAR,
   CITY_CODE VARCHAR
);
CREATE TABLE IF NOT EXISTS CITY
(
   CODE VARCHAR PRIMARY KEY,
   LABEL VARCHAR
);
ALTER TABLE INVOICE ADD CONSTRAINT BUSINESS_TRANSACTION_MOTHER FOREIGN KEY (ID) REFERENCES BUSINESS_TRANSACTION (ID);
ALTER TABLE INVOICE_LINE ADD CONSTRAINT INVOICE_INVOICE_LINES FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (ID);
ALTER TABLE INVOICE ADD CONSTRAINT CUSTOMER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID);
ALTER TABLE INVOICE_LINE ADD CONSTRAINT PRODUCT_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCT (CODE);
ALTER TABLE RECEIPT ADD CONSTRAINT BUSINESS_TRANSACTION_MOTHER FOREIGN KEY (ID) REFERENCES BUSINESS_TRANSACTION (ID);
ALTER TABLE RECEIPT_LINE ADD CONSTRAINT RECEIPT_RECEIPT_LINES FOREIGN KEY (RECEIPT_ID) REFERENCES RECEIPT (ID);
ALTER TABLE RECEIPT_LINE ADD CONSTRAINT PRODUCT_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCT (CODE);
ALTER TABLE STORE ADD CONSTRAINT CITY_CITY FOREIGN KEY (CITY_CODE) REFERENCES CITY (CODE);
COMMENT ON TABLE BUSINESS_TRANSACTION is 'A business transaction is an exchange of goods for payment.';
COMMENT ON COLUMN BUSINESS_TRANSACTION.DATE IS 'The date the transaction is executed';
COMMENT ON COLUMN BUSINESS_TRANSACTION.ID IS 'Primary Key';
COMMENT ON TABLE INVOICE is 'An invoice is a type of business transaction.';
COMMENT ON COLUMN INVOICE.TOTAL_AMOUNT IS 'The total amount of the invoice';
COMMENT ON COLUMN INVOICE.ID IS 'Primary Key';
COMMENT ON CONSTRAINT CUSTOMER_CUSTOMER ON INVOICE IS 'The invoice is linked to a customer who is a legal entity';
COMMENT ON TABLE INVOICE_LINE is 'Invoice line contains product code, number of products purchased, and purchase price.';
COMMENT ON COLUMN INVOICE_LINE.PRODUCT_CODE IS 'Code of the product';
COMMENT ON COLUMN INVOICE_LINE.QUANTITY IS 'Number of products purchased';
COMMENT ON COLUMN INVOICE_LINE.PURCHASE_PRICE IS 'Purchase price per product';
COMMENT ON COLUMN INVOICE_LINE.ID IS 'Primary Key';
COMMENT ON CONSTRAINT PRODUCT_PRODUCT ON INVOICE_LINE IS 'Invoice line is linked to a product';
COMMENT ON TABLE PRODUCT is 'Product is a bill of materials with a code and a label and a catalog price.';
COMMENT ON COLUMN PRODUCT.CODE IS 'Code of the product - Primary Key';
COMMENT ON COLUMN PRODUCT.LABEL IS 'Label of the product';
COMMENT ON COLUMN PRODUCT.CATALOG_PRICE IS 'Catalog price of the product';
COMMENT ON TABLE CUSTOMER is 'A customer who is a legal entity.';
COMMENT ON COLUMN CUSTOMER.NAME IS 'Name of the customer/legal entity';
COMMENT ON COLUMN CUSTOMER.ID IS 'Primary Key';
COMMENT ON TABLE RECEIPT is 'Receipt is a type of business transaction representing an in-store purchase.';
COMMENT ON COLUMN RECEIPT.ID IS 'Primary Key';
COMMENT ON TABLE RECEIPT_LINE is 'Receipt line linked to a product, contains number of products and store purchase price possibly discounted.';
COMMENT ON COLUMN RECEIPT_LINE.QUANTITY IS 'Number of products purchased';
COMMENT ON COLUMN RECEIPT_LINE.STORE_PURCHASE_PRICE IS 'Store purchase price, possibly discounted in marketing campaign';
COMMENT ON COLUMN RECEIPT_LINE.ID IS 'Primary Key';
COMMENT ON CONSTRAINT PRODUCT_PRODUCT ON RECEIPT_LINE IS 'Receipt line is linked to a product';
COMMENT ON TABLE STORE is 'Store is a coded list with code and label, part of retail functional area.';
COMMENT ON COLUMN STORE.CODE IS 'Code of the store - Primary Key';
COMMENT ON COLUMN STORE.LABEL IS 'Label of the store';
COMMENT ON CONSTRAINT CITY_CITY ON STORE IS 'Store is located in a city (codified list: code and label).';
COMMENT ON TABLE CITY is 'City is a codified list with code and label.';
COMMENT ON COLUMN CITY.CODE IS 'Code of the city - Primary Key';
COMMENT ON COLUMN CITY.LABEL IS 'Label of the city';
